spring:
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.71.138.38:3306/gebase
    username: MA_dou
    password: 789159357Zj
  # session 失效时间
  session:
    timeout: 86400
server:
  address: 0.0.0.0
upload:
  path: /www/wwwroot/gebase/uploadAvatarImg/
  address: http://124.71.138.38:9091/api
