spring:
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.71.138.38:3306/gebase
    username: MA_dou
    password: 789159357Zj
  # session 失效时间
  session:
    timeout: 86400
  servlet:
    multipart:
      max-request-size: 10MB # 上传文件的最大值
      max-file-size: 5MB # 单个文件上传的最大值
server:
  address: 0.0.0.0

#  web-address: http://127.0.0.1:5173/
