spring:
  profiles:
    active: dev
  application:
    name: Gebase-backend
    #本地环境
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/gebase
  # 失效时间
  session:
    timeout: 86400
  redis:
    port: 6379
    host: localhost
    # host: 线上服务器地址
    database: 1
    password:
  mvc:
    path-match:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-request-size: 10MB # 上传文件的最大值
      max-file-size: 5MB # 单个文件上传的最大值
server:
  port: 9091
  servlet:
    context-path: /api
    session:
      cookie:
        domain: localhost #线下环境 域名的访问范围
        same-site: none #线下环境 域名的访问范围
        secure: true #线下环境 域名的访问范围
#        domain: 线上服务器域名 （可以是服务器ip） #线上环境
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false # 自动转化驼峰风格
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
##本地环境
upload:
  path: D:\\项目开发\\Gebase-bankend\\src\\main\\resources\\uploadAvatarImg\\
  address: http://localhost:9091/api


#线上环境
#upload:
#  path: /www/wwwroot/gebase/uploadAvatarImg/
#  address: http://服务器地址:9091/api
